<?php
$title = 'Products List';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="tableUsers">
<tr>
    <th>Product Id</th>
    <th>Categorie Id</th>
    <th>Subcateg Id</th>
    <th>Product Name</th>    
    <th>Product Description</th>    
    <th colspan="2">Actions</th>
</tr>
<?php foreach ($products as $product) : ?>

<tr>         
    <td><?php echo $this->escapeHtml($product->product_id);?></td>
    <td><?php echo $this->escapeHtml($product->categ_id);?></td>
    <td><?php echo $this->escapeHtml($product->subcateg_id);?></td>
    <td><?php echo $this->escapeHtml($product->product_name);?></td>
    <td><?php echo $this->escapeHtml($product->product_description);?></td>
    <td class="userTableActions">
        <a href="<?php echo $this->url('products',
            array('action'=>'edit', 'product_id' => $product->product_id));?>"><li>Edit</li></a>
    </td> 
    <td class="userTableActions">    
        <a href="<?php echo $this->url('products',
            array('action'=>'delete', 'product_id' => $product->product_id));?>"><li>Delete</li></a>
    </td>
</tr>
<?php endforeach; ?>
</table>  