<?php
$title = 'Products List';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="tableUsers">
<tr>
    <th>Product Id</th>
    <th>Group Details</th>   
    <th>Product Name</th>
    <th>Product Socket</th>
    <th>Product FSB</th>
    <th>Product Memory</th>
    <th colspan="2">Actions</th>
</tr>

<?php foreach ($products as $product) : ?>

<tr>         
    <td><?php echo $this->escapeHtml($product->product_id);?></td>
    <td>
    <?php echo $this->escapeHtml($product->categ_id)." / ".$this->escapeHtml($product->subcateg_id)." / ".$this->escapeHtml($product->prod_id);?>
    </td>
    <td><?php echo $this->escapeHtml($product->product_name);?></td>
    <td>
    <?php if($product->categ_id == 1){?>
        <?php echo $this->escapeHtml($product->product_socket);?>
    <?php } else{echo "Not Suported";}?>
    </td>  
    <td>  
    <?php if($product->categ_id == 1){?>
        <?php echo $this->escapeHtml($product->product_FSB);?> Mhz
    <?php } else{echo "Not Suported";}?>
    </td>
     <td>
    <?php if($product->categ_id == 4){?>
        <?php echo $this->escapeHtml($product->product_memory_capacity)."MB / ".$this->escapeHtml($product->product_memory_type)." at ".$this->escapeHtml($product->product_memory_frequency);?> Mhz
        
     <?php }else{echo "Not Suported";}?>
     </td>
    <td class="userTableActions">
        <a href="<?php echo $this->url('products',
            array('action'=>'edit', 'product_id' => $product->product_id));?>"><li>Edit</li></a>
    </td> 
    <td class="userTableActions">    
        <a href="<?php echo $this->url('products',
            array('action'=>'delete', 'product_id' => $product->product_id));?>"><li>Delete</li></a>
    </td>
</tr>
<?php endforeach; ?>
</table>  