<?php

$title = 'Producers List';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="tableUsers">
<tr>
    <th>Producer Id</th>
    <th>Categorie Id</th>
    <th>Subcategorie Id</th>
    <th>Producer Name</th>
    <th colspan="2">Actions</th>
</tr>

<?php foreach ($producers as $producer) : ?>

<tr>         
    <td><?php echo $this->escapeHtml($producer->prod_id);?></td>
    <td><?php echo $this->escapeHtml($producer->categ_id);?></td>
    <td><?php echo $this->escapeHtml($producer->subcateg_id);?></td>
    <td><?php echo $this->escapeHtml($producer->producer_name);?></td>
    <td class="userTableActions">
        <a href="<?php echo $this->url('producers',
            array('action'=>'edit', 'prod_id' => $producer->prod_id));?>"><li>Edit</li></a>
    </td> 
    <td class="userTableActions">    
        <a href="<?php echo $this->url('producers',
            array('action'=>'delete', 'prod_id' => $producer->prod_id));?>"><li>Delete</li></a>
    </td>
</tr>
<?php endforeach; ?>
</table>  