<script src="/js/validators.js" type="text/javascript" charset="utf-8"></script>
<script src="/js/jquery.validate.min.js" type="text/javascript" charset="utf-8"></script>
<?php
$title = 'Sign Up';
$this->headTitle($title);
?>
<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'formSignUp');
$form->setAttribute('class', 'form-signin');
?>
<div id="carbonForm">
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="fieldContainer">
<?php echo $this->form()->openTag($form) ?>

    <?php foreach ($form as $element): ?>
        
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            
                    <input class="btn btn-primary" type="submit" value="Sign up" id="login-btn">
              
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
        <?php else: ?>       
                    <div class="control-group">
                        <div class="controls">
                        <?php if($element->getName() == 'user_type'){?>
                         <input type="<?=(strpos($element->getName(),'password')!==false ? 'password':'hidden')?>" class="input-block-level" name='<?=$element->getName()?>' id='<?=$element->getName()?>' autofocus="autofocus" placeholder="<?=$element->getLabel()?>" value="<?=$element->getValue()?>">
                         <?php }else if($element->getName() == 'registration_time'){?>
                         <input type="<?=(strpos($element->getName(),'registration_time')!==false ? 'hidden':'text')?>" class="input-block-level" name='<?=$element->getName()?>' id='<?=$element->getName()?>' autofocus="autofocus" placeholder="<?=$element->getLabel()?>" value="<?=$element->getValue()?>">                
                        <?php }else{?>
                            <input type="<?=(strpos($element->getName(),'password')!==false ? 'password':'text')?>" class="input-block-level" name='<?=$element->getName()?>' id='<?=$element->getName()?>' autofocus="autofocus" placeholder="<?=$element->getLabel()?>" value="<?=$element->getValue()?>">              
                <?php }?>
                <span class="help-inline" >
                <ul>
                    <li class="liNoP" id="<?php echo "error_".$element->getName(); ?>"><?=$this->formElementErrors($element)?></li>
                </ul>  
                </span>
                        </div>
                    </div>
                    
                
        <?  }?>
        
        <?php endif ?>
    <?php endforeach ?>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>

<?php echo $this->form()->closeTag() ?>
</div>
</div>