<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'target');
$form->setAttribute('class', 'form-signin');
?>

<?php echo $this->form()->openTag($form) ?>

    <?php foreach ($form as $element): ?>
        <?
        if($this->formElementErrors($element)){
            $error = true;
        }else{
            $error = false;
        }
        ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            <div class="control-group no-border">
                <div style="text-align: right;">
                    <input class="btn btn-primary" type="submit" value="Sign up" id="login-btn">
                </div>
            </div>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
        <?php else: ?>
        
        <?    if($element->getName() == "user_type"){
                echo $this->formHidden($form->get($element->getName())); 
            }else{
            
                ?>
                    <div class="control-group <?=($error ? "error" : "")?>">
                        <div class="controls">
                            <input type="<?=(strpos($element->getName(),'password')!==false ? 'password':'text')?>" class="input-block-level" name='<?=$element->getName()?>' autofocus="autofocus" placeholder="<?=$element->getLabel()?>" value="<?=$element->getValue()?>">
                            <span class="help-inline" ><?=$this->formElementErrors($element)?></span>
                        </div>
                    </div>
                    
                
        <?  }?>
        
        <?php endif ?>
    <?php endforeach ?>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>

<?php echo $this->form()->closeTag() ?>