 <div class="productleftSidebar hero-unit">
    <div class="sidebarProductTitle">Related Products</div>
 <?php if($this->sb_product>0){
        foreach($this->sb_product as $row){?>
     <div class="img-polaroid sidebarProduct">
        <div class="sidebarProductName">                
            <?=$row['name']?>                
        </div> 
        <div class="sidebarProductContent"> 
            <?= substr($row['description'], 0, 90)."..."?><a href="<?=$this->url('index', array('action' => 'product','product' => $row['product'], 'name' => $row['name'], 'id' => $row['id']));?>">read more</a>  
        </div>
     </div>                         
        <?php } }?>
   
</div> 
<div class="productsContainer hero-unit">  
<?php 
if($this->categ>0){
 foreach($this->categ as $row){?>      
<div class="manufacturer">
    
     <a href="<?=$this->url('index', array('action' => 'products','categorie' => $row['type']));?>"><img src="<?=SERVER_URL?>/img/product_type/<?=$row['img']?>" width="200px" height="200px"></a>
        <div class="categURL">
        
        </div>
        <a class="categURLa" href="<?=$this->url('index', array('action' => 'products', 'categorie' => $row['type']));?>"><?=$row['full_name']?>'s</a>
</div>
 <?php }}?>
</div>
 
