<?php 
    if($this->result>0){
        foreach($this->result as $row){?>      
            <div id="manufacturer">
            <?=$row['product_description']?>
                <div class="manufacturerContainer">    
                    <h1><a href="<?=$this->url('manufacturer', array('action' => 'manufacturer', 'id' => $row['product_id']));?>"><?=$row['product_name']?></a></h1> 
                </div>
            </div>
        <?php
        } ?>
  
<?php }?>
 
