<?php
           

    if($this->product>0){
        foreach($this->product as $row){?>
<div class="product">
<div class="productName">                
                 <a href="<?=$this->url('categories', array('action' => 'product', 'product' => $row['product_name'],'id' => $row['product_id']));?>"><?=$row['name']?></a>                
                 </div> 
              <div class="productContent"> 
                  <?= substr($row['description'], 0, 120)."..."?><a href="<?=$this->url('categories', array('action' => 'product', 'product' => $row['product_name'],'id' => $row['product_id']));?>">read more</a>  
                 </div>                
            </div>
        <?php
        } ?>
  
<?php }?>
 
