<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Hardware Compare'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') 
                                      ->prependFile($this->basePath() . '/js/jquery-1.8.1.min.js')  ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Hardware Compare') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>                                                        
                            <?php if($this->zfcUserIdentity() and $this->zfcUserIdentity()->getUserType() == 1){?>
                            <li class="active"><a href="<?php echo $this->url('users')?>">Users</a></li>
                            <li class="active"><a href="<?php echo $this->url('categories')?>">Categories</a></li>
                            <li class="active"><a href="<?php echo $this->url('subcategories')?>">Subcategories</a></li>
                            <?php }?>
                            <?php if($this->zfcUserIdentity()){?>                    
                            <li class="active"><a href="<?php echo $this->url('zfcuser/logout')?>">Logout</a></li>
                             <li class="welcome">Welcome : <?php echo $this->zfcUserIdentity()->getDisplayname(); ?></li>
                             <?php }else{?>
                             <li class="active"><a href="<?php echo $this->url('zfcuser/register')?>">Sign Up</a></li>
                             <li class="active"><a href="<?php echo $this->url('zfcuser/login')?>">Login </a></li>                           
                                                        
                             <?php }?>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>Copyright @ <?php echo date('Y') ?> Kaius Plesa. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
