<?php

$title = 'Categories List';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="tableUsers">
<tr>
    <th>Categorie Id</th>
    <th>Categorie Name</th>
    <th colspan="2">Actions</th>
</tr>
<?php foreach ($categories as $categorie) : ?>
<tr>         
    <td><?php echo $this->escapeHtml($categorie->categ_id);?></td>
    <td><?php echo $this->escapeHtml($categorie->categorie_name);?></td>
    <td class="userTableActions">
        <a href="<?php echo $this->url('categories',
            array('action'=>'edit', 'categ_id' => $categorie->categ_id));?>"><li>Edit</li></a>
    </td> 
    <td class="userTableActions">    
        <a href="<?php echo $this->url('categories',
            array('action'=>'delete', 'categ_id' => $categorie->categ_id));?>"><li>Delete</li></a>
    </td>
</tr>
<?php endforeach; ?>
</table>  