<?php

$title = 'Sign Up';
$this->headTitle($title);
?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('users', array('action' => 'add')));
$form->prepare();

?>
<div id="carbonForm">
    <h1><?php echo $this->escapeHtml($title); ?></h1>

        <div class="fieldContainer">
            <?php
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('id_user'));
                echo $this->formRow($form->get('name'));
                echo $this->formRow($form->get('username'));
                echo $this->formRow($form->get('password'));
                echo $this->formRow($form->get('email'));                
                //echo $this->formCollection($form);
                
            ?>          
        </div>

        <div class="signupButton">
            <?php
                echo $this->formSubmit($form->get('submit'));
            ?>     
        </div>
            <?php
                echo $this->form()->closeTag();
            ?>
</div>