<?php

$title = 'Delete user';
$this->headTitle($title);
?>
<?php
$url = $this->url('users', array(
    'action' => 'delete',
    'id_user'     => $this->id_user,
));

?>
<div class="delConf">
<h1><?php echo $this->escapeHtml($title); ?> : 
    <?php echo $this->escapeHtml($users->username); ?>?
</h1>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id_user" value="<?php echo (int) $users->id_user; ?>" />
    <input type="submit" name="del" value="Yes" class="delButtonConf" />
    <input type="submit" name="del" value="No" class="delButtonConf" />
</div>
</div>
</form>