<?php

$title = 'Delete user';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($users->name); ?>' by
    '<?php echo $this->escapeHtml($users->username); ?>'?
</p>
<?php
$url = $this->url('users', array(
    'action' => 'delete',
    'id_user'     => $this->id_user,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id_user" value="<?php echo (int) $users->id_user; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>