<?php

$title = 'Edit User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'users',
    array(
        'action' => 'edit',
        'id_user'     => $this->id_user,
    )
));
 echo $this->id_user; 
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id_user'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('email'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();