<?php

$title = 'Users List';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('users', array('action'=>'add'));?>">Sign Up</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>Username</th>
    <th>Email Address</th>
    <th>User Type</th>
    <th>Last Login</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($users as $user) : ?>
<tr>      
    <?php 
        $type = $this->escapeHtml($user->user_type);
        $type == 1 ? $type = 'Admin': $type='Member';
     ?> 
    <td><?php echo $this->escapeHtml($user->name);?></td>
    <td><?php echo $this->escapeHtml($user->username);?></td>
    <td><?php echo $this->escapeHtml($user->email);?></td>
    <td><?php echo $type;?></td>
    <td><?php echo date("l jS F Y - g:ia",$this->escapeHtml($user->last_login));?></td>
    <td>
        <a href="<?php echo $this->url('users',
            array('action'=>'edit', 'id_user' => $user->id_user));?>">Edit</a>
        <a href="<?php echo $this->url('users',
            array('action'=>'delete', 'id_user' => $user->id_user));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>